import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Homepage from '@/components/homepage/homepage';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>    

      <Homepage data={data}/>
            
    </>
  );
}

export const getServerSideProps = async () => {
  const data = await import('./../data/data.json');
  return { props: { data: data.events_categories } };
};
